# Generated by Django 4.2.3 on 2023-07-27 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('standard', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('parent_contact_number', models.BigIntegerField()),
                ('profile_image', models.ImageField(blank=True, upload_to='images/profile/')),
                ('course', models.ManyToManyField(blank=True, to='my_app.course')),
            ],
            options={
                'verbose_name': 'Student Detail',
                'verbose_name_plural': 'Students Detail',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.course')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='my_app.students')),
            ],
        ),
    ]
