# Generated by Django 4.2.3 on 2023-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student Detail', 'verbose_name_plural': 'Student Details'},
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/profile/'),
        ),
    ]
