# Generated by Django 4.2.3 on 2023-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(default='', max_length=100)),
                ('stu_roll', models.IntegerField()),
                ('stu_class', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student Detail',
            },
        ),
    ]
