# Generated by Django 4.2.3 on 2023-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stu_class',
            field=models.IntegerField(verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_name',
            field=models.CharField(default='', max_length=100, verbose_name='Student name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_roll',
            field=models.IntegerField(verbose_name='Roll No.'),
        ),
    ]
