# Generated by Django 4.2.3 on 2023-08-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_student_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
