# Generated by Django 4.2.3 on 2023-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(default='model_group', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
