# Generated by Django 4.2.3 on 2023-08-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_place_delete_student_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_app.place')),
                ('customers', models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', to='test_app.place')),
            ],
            bases=('test_app.place',),
        ),
    ]
