# Generated by Django 4.2.3 on 2023-08-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_group_person_membership_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
