# Generated by Django 4.2.3 on 2023-08-03 13:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_students_stu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 18, 22, 53, 274995)),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 18, 22, 53, 274995)),
        ),
    ]
