# Generated by Django 4.2.3 on 2023-08-08 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_students_age_alter_students_stu_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 15, 33, 36, 484966)),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 15, 33, 36, 484966)),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='my_app.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.artist'),
        ),
    ]
